version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: pull submodules
          command: |
            git submodule init
            git submodule update --remote

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
      - run:
          name: build
          command: |
            . venv/bin/activate
            python setup.py install

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ls -al
            pytest

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
